# Generated by Django 4.2.13 on 2026-06-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(blank=True, max_length=500, unique=True)),
                ("source", models.CharField(max_length=100)),
                ("article_url", models.URLField(max_length=1000, unique=True)),
                ("published_date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Polity", "Polity & Governance"),
                            ("Economy", "Economy & Finance"),
                            ("Science", "Science & Technology"),
                            ("International", "International Relations"),
                            ("Environment", "Environment & Ecology"),
                            ("Awards", "Awards & Honours"),
                            ("Sports", "Sports"),
                            ("Tamil Nadu", "Tamil Nadu"),
                            ("Others", "Others"),
                        ],
                        default="Others",
                        max_length=50,
                    ),
                ),
                ("summary", models.TextField(help_text="2-line TNPSC focused summary")),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("mcq_question", models.TextField(blank=True, null=True)),
                (
                    "mcq_options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dictionary like {'A': '...', 'B': '...'}",
                    ),
                ),
                (
                    "mcq_answer",
                    models.CharField(
                        blank=True,
                        help_text="Correct option key, e.g., 'A', 'B', 'C', 'D'",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("mcq_explanation", models.TextField(blank=True, null=True)),
                ("highlighted_entities", models.JSONField(blank=True, default=dict)),
                (
                    "revision_notes",
                    models.TextField(
                        blank=True,
                        help_text="Bullet points for quick revision",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "News Articles",
                "ordering": ["-published_date", "-created_at"],
            },
        ),
    ]
