# Generated by Django 4.2.13 on 2026-06-15 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.IntegerField(default=0)),
                ("quiz_attempts", models.IntegerField(default=0)),
                ("date", models.DateField()),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="news.news",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Analytics Data",
                "unique_together": {("news", "date")},
            },
        ),
    ]
